# Generated by Django 3.0.5 on 2020-05-24 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20200524_1800'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tags',
            new_name='Tests',
        ),
    ]
